
-- 🌈 Script แบบ OpenSource แต่เพื่อความะดวกสำหรับการอัพเดท [ 💚 Source ที่อยู่ใน github เมื่อเสร็จและส่งงานเสร็จสิ้น จะลบทันที ]
-- >> Thankful for hire Me : https://discord.gg/5u5Mw84afM << UPDATE [< Lumina Script >]

_G.WhatMap = "BloxSpin"
_G.Configs = {
    Items = {"Pool Cue"},
} -- configs เพิ่มเติม
loadstring(game:HttpGet("https://raw.githubusercontent.com/Tarzzth/Roblox-work-expilot/refs/heads/main/Loader.lua"))()
